# Assignment 3

## Load all libraries
```{r, warning=FALSE, message=FALSE}
library(magrittr)
library(readr)
library(dplyr)
library(tidyr)
library(factoextra)
library(matrixStats)
library(ggalluvial)
library(ComplexHeatmap)
```

## Get 5000 most variable genes

This code chunk only needs to be run once to generate the topGenes.RDS file.
One the RDS object has been generated, skip straight to "Read in data".
```{r}
deseq <- readRDS("deseq.RDS")
deseq_df <- readRDS("deseq_df.RDS")
collapsed_mapping_df <- readRDS("collapsed_mapping_df.RDS")

deseq_df <- deseq_df %>%
  inner_join(collapsed_mapping_df, by = c("Gene" = "ensembl_gene_id"))
mat <- counts(deseq, normalized = T)[deseq_df$Gene,]

topGenesMat <- head(order(rowVars(mat), decreasing = TRUE), 5000)
topGenes <- mat[topGenesMat,]

topGenesMat <- head(order(rowVars(mat), decreasing = TRUE), 10000)
topGenes10k <- mat[topGenesMat,]

saveRDS(topGenes, "topGenes.RDS")
saveRDS(topGenes10k, "topGenes10k.RDS")
```

## Read in data
```{r, message=FALSE}
topGenes <- readRDS("topGenes.RDS")
topGenes10k <- readRDS("topGenes10k.RDS")

topGenes <- t(topGenes)
topGenes10k <- t(topGenes10k)

topGenes_df <- as.data.frame(topGenes)
topGenes10k_df <- as.data.frame(topGenes10k)

metadata <- read_tsv("SRP119064/metadata_SRP119064.tsv")
```

## K-means
```{r}
set.seed(999)

# Check optimal number of clusters
fviz_nbclust(x = topGenes, FUNcluster = kmeans, method="wss")

# 1 cluster
km_res_1 <- kmeans(x = topGenes, centers = 1, iter.max = 10, nstart = 25)

# 2 clusters | This is the ideal number
km_res_2 <- kmeans(x = topGenes, centers = 2, iter.max = 10, nstart = 25)

# 3 clusters 
km_res_3 <- kmeans(x = topGenes, centers = 3, iter.max = 10, nstart = 25)

# Visualize clusters
fviz_cluster(km_res_2, topGenes, geom = ("point"))

# Top 10 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:10])
km_res_top10 <- kmeans(x = topGenes_df_test, centers = 2, iter.max = 10, nstart = 25)

# Top 100 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:100])
km_res_top100 <- kmeans(x = topGenes_df_test, centers = 2, iter.max = 10, nstart = 25)

# Top 1000 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:1000])
km_res_top1000 <- kmeans(x = topGenes_df_test, centers = 2, iter.max = 10, nstart = 25)

# Top 10k genes
km_res_top10k <- kmeans(x = topGenes10k_df, centers = 2, iter.max = 10, nstart = 25)

# Alluvial diagram
km_alluvial_df <- as.data.frame(km_res_top10$cluster)
km_alluvial_df <- cbind(km_alluvial_df,
                     as.data.frame(km_res_top100$cluster),
                     as.data.frame(km_res_top1000$cluster),
                     as.data.frame(km_res_top10k$cluster),
                     metadata$refinebio_specimen_part)
colnames(km_alluvial_df) <- c("ten_genes", "hun_genes", "thou_genes", "tenthou_genes", "brain_part")

# Put into alluvial format
km_alluvial_df <- km_alluvial_df %>%
                  group_by(ten_genes, hun_genes, thou_genes, tenthou_genes, brain_part) %>%
                  summarise(freq = n())

# Plot alluvial diagram
ggplot(km_alluvial_df,
       aes(y = freq, axis1 = ten_genes, axis2 = hun_genes, axis3 = thou_genes, axis4 = tenthou_genes)) +
  geom_alluvium(aes(fill = brain_part), width = 1/12) +
  geom_stratum(width = 1/8, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("10 genes", "100 genes", "1000 genes", "10k genes"), expand = c(.02, .02)) +
  ylab("Frequency") +
  guides(fill = guide_legend(title = "Brain part")) +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  ggtitle("Clustering setups and cluster membership")
```

## Hierarchical Clustering
```{r}
set.seed(999)

# Check optimal number of clusters
fviz_nbclust(x = topGenes, FUNcluster = hcut, method="wss")

distance <- dist(topGenes_df, method = "euclidean")
hc_res  <- hclust(distance, method = "complete")
hc.cut <- cutree(hc_res, k = 2)

# 1 cluster
hc_res_1 <- cutree(hc_res, k = 1)
table(hc_res_1)

# 2 clusters | This is the ideal number
hc_res_2 <- cutree(hc_res, k = 2)
table(hc_res_2)

# 3 clusters 
hc_res_3 <- cutree(hc_res, k = 3)
table(hc_res_3)

# Visualize dendrogram
h <- plot(hc_res, cex = 0.6, hang = -1)
rect.hclust(hc_res, k = 2, border = 2:5)

# Visualize clusters
fviz_cluster(list(data = topGenes, cluster = hc_res_2), geom = ("point"))

# Top 10 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:10])
distance <- dist(topGenes_df_test, method = "euclidean")
hc_res_top10  <- hclust(distance, method = "complete")

plot(hc_res_top10, cex = 0.6, hang = -1)
hc.cut10 <- cutree(hc_res_top10, k = 2)
table(hc.cut10)
fviz_cluster(list(data = topGenes, cluster = hc.cut10), geom = ("point"))

# Top 100 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:100])
distance <- dist(topGenes_df_test, method = "euclidean")
hc_res_top100  <- hclust(distance, method = "complete")

plot(hc_res_top100, cex = 0.6, hang = -1)
hc.cut100 <- cutree(hc_res_top100, k = 2)
table(hc.cut100)
fviz_cluster(list(data = topGenes, cluster = hc.cut100), geom = ("point"))

# Top 1000 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:1000])
distance <- dist(topGenes_df_test, method = "euclidean")
hc_res_top1000  <- hclust(distance, method = "complete")

plot(hc_res_top1000, cex = 0.6, hang = -1)
hc.cut1000 <- cutree(hc_res_top1000, k = 2)
table(hc.cut1000)
fviz_cluster(list(data = topGenes, cluster = hc.cut1000), geom = ("point"))

# Top 10k genes
distance <- dist(topGenes10k_df, method = "euclidean")
hc_res_top10k  <- hclust(distance, method = "complete")

plot(hc_res_top10k, cex = 0.6, hang = -1)
hc.cut10k <- cutree(hc_res_top10k, k = 2)
table(hc.cut10k)
fviz_cluster(list(data = topGenes, cluster = hc.cut10k), geom = ("point"))

# Alluvial diagram
hc_alluvial_df <- as.data.frame(hc.cut10)
hc_alluvial_df <- cbind(hc_alluvial_df,
                     as.data.frame(hc.cut100),
                     as.data.frame(hc.cut1000),
                     as.data.frame(hc.cut10k),
                     metadata$refinebio_specimen_part)
colnames(hc_alluvial_df) <- c("ten_genes", "hun_genes", "thou_genes", "tenthou_genes", "brain_part")

# Put into alluvial format
hc_alluvial_df <- hc_alluvial_df %>%
                  group_by(ten_genes, hun_genes, thou_genes, tenthou_genes, brain_part) %>%
                  summarise(freq = n())

# Plot alluvial diagram
ggplot(hc_alluvial_df,
       aes(y = freq, axis1 = ten_genes, axis2 = hun_genes, axis3 = thou_genes, axis4 = tenthou_genes)) +
  geom_alluvium(aes(fill = brain_part), width = 1/12) +
  geom_stratum(width = 1/8, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("10 genes", "100 genes", "1000 genes", "10k genes"), expand = c(.02, .02)) +
  ylab("Frequency") +
  guides(fill = guide_legend(title = "Brain part")) +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  ggtitle("Clustering setups and cluster membership")
```

## PAM Clustering
```{r}
library(cluster)

set.seed(999)

# Check optimal number of clusters
fviz_nbclust(x = topGenes, FUNcluster = pam, method = "wss")

# 1 cluster
pam_res_1 <- pam(x = topGenes, k = 1)

# 2 clusters
pam_res_2 <- pam(x = topGenes, k = 2)

# 3 clusters
pam_res_3 <- pam(x = topGenes, k = 3)

# Visualize clusters
fviz_cluster(pam_res_4, data = topGenes, geom = "point")

# Top 10 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:10])
pam_res_top10 <- pam(x = topGenes_df_test, k = 2)

# Top 100 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:100])
pam_res_top100 <- pam(x = topGenes_df_test, k = 2)

# Top 1000 genes
topGenes_df_test <- as.data.frame(topGenes_df[,1:1000])
pam_res_top1000 <- pam(x = topGenes_df_test, k = 2)

# Top 10k genes
pam_res_top10k <- pam(x = topGenes10k_df, k = 2)

cluster_data <- data.frame(
  "Original" = km_res_4$cluster,
  "PAM_2" = pam_res_2$clustering,
  "PAM_3" = pam_res_3$clustering,
)

ggplot(cluster_data, aes(axis1 = Original, axis2 = PAM_2, y = after_stat(stratum))) +
  geom_alluvium(aes(fill = as.factor(Original))) +
  geom_stratum(aes(fill = as.factor(PAM_2))) +
  scale_x_discrete(limits = c("Original", "PAM_2", "PAM_3")) +
  scale_fill_manual(values = c("orange", "pink")) +
  theme_void() +
  labs(title = "Alluvial Diagram (how different clustering setups changed cluster memberships):",
       x = "Clustering Setup",
       y = "Sample ID")

```

## Heatmaps & dendrograms
```{r, message=FALSE}
# Prepare expression data
topGenes_hm <- t(topGenes)
topGenes_hm <- log2(topGenes_hm)
topGenes_hm[topGenes_hm == -Inf] <- 0

# K-means clustering

# Prepare annotation data
annot_df <- as.data.frame(cbind(metadata$refinebio_specimen_part,
                                km_res_2$cluster))

colnames(annot_df) <- c("Brain_part", "Kmean_cluster")

# Colors were taken from https://davidmathlogic.com/colorblind/
sample_annot <- HeatmapAnnotation(df = annot_df,
                                  col = list(Brain_part = c("cortex" = "#E1BE6A", "hippocampus" = "#40B0A6"),
                                             Kmean_cluster = c("1" = "#1A85FF", "2" = "#D41159")),
                                  annotation_label = c("Brain part", "K-mean cluster"))

heatmap <- Heatmap(topGenes_hm,
                   name = "Log-normalized counts",
                   row_title = "Genes",
                   column_title = "Samples",
                   show_row_names = FALSE,
                   show_column_names = FALSE,
                   top_annotation = sample_annot)



# Hierarchical Clustering

# Prepare annotation data
annot_df_hc <- as.data.frame(cbind(metadata$refinebio_specimen_part,
                                hc.cut))

colnames(annot_df_hc) <- c("Brain_part", "Kmean_cluster")

# Colors were taken from https://davidmathlogic.com/colorblind/
sample_annot_hc <- HeatmapAnnotation(df = annot_df_hc,
                                  col = list(Brain_part = c("cortex" = "#E1BE6A", "hippocampus" = "#40B0A6"),
                                             Hier_cluster = c("1" = "#1A85FF", "2" = "#D41159")),
                                  annotation_label = c("Brain part", "Hierarchical cluster"))

heatmap <- Heatmap(topGenes_hm,
                   name = "Log-normalized counts",
                   row_title = "Genes",
                   column_title = "Samples",
                   show_row_names = FALSE,
                   show_column_names = FALSE,
                   top_annotation = sample_annot_hc)
```

## Statistics
```{r}
# Brain part membership, 1 is hippocampus, 2 is cortex
brain_mapping <- metadata %>%
  select(refinebio_accession_code, refinebio_specimen_part)
brain_mapping$refinebio_specimen_part[brain_mapping$refinebio_specimen_part == "hippocampus"] <- 1
brain_mapping$refinebio_specimen_part[brain_mapping$refinebio_specimen_part == "cortex"] <- 2

# K-Means



# Hierarchical Clustering

# Cluster membership, 5000 genes & k=2
hc_clusters <- data.frame(refinebio_accession_code  = names(hc.cut[which(hc.cut[]==1)]), cluster_group = 1)
hc_clusters_cluster2 <- data.frame(refinebio_accession_code  = names(hc.cut[which(hc.cut[]==2)]), cluster_group = 2)
hc_clusters <- rbind(hc_clusters, hc_clusters_cluster2)

# Data frame
hc_chi_df <- hc_clusters %>%
  merge(brain_mapping, by = c("refinebio_accession_code" = "refinebio_accession_code")) %>%
  column_to_rownames("refinebio_accession_code")

# Chi-squared test
chisq <- chisq.test(hc_chi_df$refinebio_specimen_part, hc_chi_df$cluster_group)
p_adj <- p.adjust(chisq$p.value,method="bonferroni")


# PAM Clustering

```