# Assignment 1

## Load all libraries
```{r, warning=FALSE}
library("org.Mm.eg.db")
library(magrittr)
library(readr)
library(dplyr)
library(tidyr)
library(biomaRt)
library(ggfortify)
library(DESeq2)
library(ggplot2)
library(tibble)
library(EnhancedVolcano)
```

## Read in data
Data will be in a folder called "SROP119064".
```{r warning=FALSE}
# Read in metadata
metadata <- read_tsv("SRP119064/metadata_SRP119064.tsv")

# Read in data
expression_df <- read_tsv("SRP119064/SRP119064.tsv")%>%
  # Convert Gene ID column to rowname
  column_to_rownames("Gene")

# Align data and metadata
# Select from expression_df the rows with metadata's refinebio_accession_code
expression_df <- expression_df %>%
  dplyr::select(metadata$refinebio_accession_code)

# Check that they are in the same order
all.equal(colnames(expression_df), metadata$refinebio_accession_code)

expression_df <- expression_df %>%
  rownames_to_column("Gene")

mart <- useMart('ensembl', dataset = 'mmusculus_gene_ensembl')
```

## Get gene names
```{r}
mapping_ensembl_to_symbol <- getBM(
  attributes = c(
    'ensembl_gene_id', 'mgi_symbol'),
  values = expression_df$Gene,
  mart = mart)

collapsed_mapping_df <- mapping_ensembl_to_symbol %>%
  # Group by Ensembl IDs
  group_by(ensembl_gene_id) %>%
  # Collapse the mgi symbols `mapping_df` into one column named `all_symbols`
  summarize(all_symbols = paste(mgi_symbol, collapse = ";"))

final_mapping_df <- collapsed_mapping_df %>%
  # Add the rest of the expression data
  right_join(expression_df, by = c("ensembl_gene_id" = "Gene"))
```

## Write data to output file
```{r}
# Write data frame to output file
write_tsv(final_mapping_df, file.path(
  "results/SRP040561_GeneNames.tsv"
))
```

## Create density plot
```{r}
logged_mapping <- final_mapping_df %>% 
  column_to_rownames("ensembl_gene_id") %>%
  dplyr::select_if(is.numeric) %>%
  log()

per_gene_median_expressions <- logged_mapping %>%
  rowwise() %>%
  mutate(per_gene_medians = median(c_across(where(is.numeric)), na.rm=TRUE)) %>%
  dplyr::select(per_gene_medians)

ggplot(per_gene_median_expressions, aes(x=per_gene_medians)) + 
  geom_density()
```

## Create PCA plot
```{r}
final_mapping_df <- final_mapping_df %>%
  column_to_rownames("ensembl_gene_id") %>%
  dplyr::select(metadata$refinebio_accession_code)

# Check that they are in the same order
all.equal(colnames(final_mapping_df), metadata$refinebio_accession_code)

gene_matrix <- round(final_mapping_df)

metadata <- metadata %>%
  # Get trem2knockout status
  dplyr::mutate(knockout_status = dplyr::case_when(
    stringr::str_detect(refinebio_subject, "wt") ~ "wt",
    stringr::str_detect(refinebio_subject, "trem2ko") ~ "trem2ko"
  )) %>%
  # Get time passed (4 months or 8 months)
  dplyr::mutate(time_passed = dplyr::case_when(
    stringr::str_detect(refinebio_subject, "4m") ~ "4m",
    stringr::str_detect(refinebio_subject, "8m") ~ "8m"
  ))
metadata <- metadata %>%
  dplyr::mutate(
    # Here we define the values our factor variable can have and their order.
    knockout_status = factor(knockout_status, levels = c("wt", "trem2ko"))
  ) %>%
  dplyr::mutate(
    refinebio_specimen_part = factor(refinebio_specimen_part, levels = c("cortex", "hippocampus"))
  ) %>%
  dplyr::mutate(
    time_passed = factor(time_passed, levels = c("4m", "8m"))
  )

deseq <- DESeqDataSetFromMatrix(gene_matrix, metadata, ~refinebio_specimen_part)
deseq <- DESeq(deseq)

plotPCA(DESeqTransform(deseq), intgroup = "refinebio_specimen_part")
```

## Complete differential expression analysis
```{r}
# Set seed for jitter plot
set.seed(999)

all.equal(colnames(final_mapping_df), metadata$refinebio_accession_code)

# Minimum counts cutoff
# Dataset is much bigger than the tutorial's dataset; ~80 times bigger
# Thus, we set the minimum count to 500 instead of 10 (~50 times more)
filtered_expression_df <- final_mapping_df %>%
  dplyr::filter(rowSums(.) >= 500)

# Dataset reduced to 18997 genes
nrow(filtered_expression_df)

# Change all counts to integers
gene_matrix <- round(filtered_expression_df)

ddset <- DESeqDataSetFromMatrix(
  countData = gene_matrix,
  colData = metadata,
  design = ~refinebio_specimen_part
)

deseq <- DESeq(ddset)
deseq_results <- results(deseq)

# Get shrunken log fold change estimates to decrease noise and preserve large differences between groups
deseq_results <- lfcShrink(
  deseq,
  coef = 2,
  res = deseq_results
)

# Table of DEG
deseq_df <- deseq_results %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>%
  dplyr::mutate(threshold = padj < 0.05) %>%
  dplyr::arrange(dplyr::desc(log2FoldChange))

# Save and summarize findings
write_tsv(deseq_df, file.path("results/SRP040561_DEG_results.tsv"))

```

## Volcano plot
```{r}
volcano_plot <- EnhancedVolcano(
  deseq_df,
  lab = deseq_df$Gene,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = 0.01
)

png(filename = "results/SRP040561_volcano_plot.png")
volcano_plot
dev.off()
```